### PR TITLE
Independent values can be suggested for concurrent edits

### PR DESCRIPTION
**Pull request by jbo-ableton**
Such that multiple input devices can be used to attempt edits on the
same set of variables.

### CODE REVIEW

**Comment by jbo-ableton** [comment]
@Nocte- what is the problem with AppVeyor? It seems not related to the patch to me :/

**Comment by Nocte-** [comment]
Thanks for the patch!

**Comment by Nocte-** [comment]
And I have no idea what's up with AppVeyor, it used to work fine. I'll go take a look.

**Comment by jbo-ableton** [comment]
Thanks for merging it. Btw, I didn't dare to touch the `suggest_value` function, but I was wondering if the semantics should be changed to only affect the newest edit constraint in the stack... Either way works for me anyways, but just thinking...

**Pull request merged**
